// monolit-app/webshop-front/src/app/components/add-campaign/add-campaign.component.ts
import { DatePipe } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { ToastrService } from 'ngx-toastr';
import { CampaignService } from 'src/app/service/campaign.service';
import { getRoleFromToken, getUsernameFromToken } from 'src/app/util/tokenUtil';

@Component({
  selector: 'app-add-campaign',
  templateUrl: './add-campaign.component.html',
  styleUrls: ['./add-campaign.component.css'],
})
export class AddCampaignComponent implements OnInit {

  campaign: any = {
    username: getUsernameFromToken(),
    campaignType: 'POST',
    termType:'SHORT_TERM',
    startDate: '',
    endDate: '',
    perDay: 1,
    audiences: new Array(),
    ads: new Array()
  };
  files = new Array();
  file: any = null;
  imagesToUpload: any = null;
  ad = {
      url: '',
      description: '',
      fileName: ''
  };
  targetedAudience = {
      fromAge: 15,
      toAge: 70,
      hashtags: new Array(),
      genders: new Array()
  };

  isLongTerm: boolean = false;
  time: any = {hours: '', minutes: ''};
  duration: number = 1;
  hashtags: string = '';
  gender = {
       male: false,
       female: false,
       other: false   
  };

  constructor(private toastrService: ToastrService,
              private datePipe: DatePipe,
              private modalService: NgbModal,
              private router: Router,
              private campaignService: CampaignService) { }

  ngOnInit(): void {
    if(getRoleFromToken() != 'ROLE_AGENT')
      this.router.navigate(["/discover"]);
  }

  createCampaign(){
    if(!this.campaign.startDate){
      this.toastrService.warning("Please select start date")
      return
    }
    if(this.isLongTerm)
      this.campaign.termType = "LONG_TERM"
    else
      this.campaign.termType = "SHORT_TERM"

    if(this.campaign.termType == "LONG_TERM"){
        if(this.duration < 1 || !this.duration){
          this.toastrService.warning("Invalid duration field format")
          return;
        }
        if(this.campaign.perDay < 1 || this.campaign.perday > 24 || !this.campaign.perDay){
          this.toastrService.warning("Invalid per day field format (min=0, max=24)")
        }
        let date = new Date(this.campaign.startDate);
        date.setDate(date.getDate() + Number(this.duration));
        this.campaign.endDate = this.datePipe.transform(date, 'yyyy-MM-dd')?.toString();
    }else if(this.campaign.termType == "SHORT_TERM"){
      if(this.time.hours < 0 || this.time.hours > 23 || !this.time.hours){
        this.toastrService.error("Invalid hours field format")
        return;
      }
      if(this.time.minutes < 0 || this.time.minutes > 59 || !this.time.minutes){
        this.toastrService.error("Invalid minutes field format")
        return;
      }
        this.campaign.startDate = this.campaign.startDate + " " + this.formatTime();
    }

    this.imagesToUpload = new FormData();
    for(let file of this.files)
        this.imagesToUpload.append("file", file);

    // TODO: Add images to server
    this.campaignService.uploadImages(this.imagesToUpload).subscribe(data => {
      this.toastrService.success("Files added successfully")    
    }, err => {
      this.toastrService.error("Something went wrong while creating campaign");
    })

    this.campaignService.createCampaign(this.campaign).subscribe(() => {
      this.toastrService.success("Campaign made successfully");
    }, err => {
      this.toastrService.error("Something went wrong while creating campaign");
    })
    
  }

  addAd(){
    if(this.file == null){
        this.toastrService.warning("Media must be specified!")
        return;
    }
    this.files.push(this.file);
    this.ad.fileName = this.file.name;
    this.file = null;
    this.campaign.ads.push(this.ad);
    this.ad = {
        url: '',
        description: '',
        fileName: ''
    }

    this.modalService.activeInstances.closed = true;
  }

  onImageUpload(event:any){
    this.file = event.target.files[0];
  }


  removeAd(i: number){
    this.campaign.ads.splice(i, 1);
    this.files.splice(i, 1);
  }

  addAudience(){
    if(this.targetedAudience.fromAge > this.targetedAudience.toAge){
        this.toastrService.warning("Invalid age range!");
        return;
    }
    if(this.gender.male)
      this.targetedAudience.genders.push("MALE");
    if(this.gender.female)
      this.targetedAudience.genders.push("FEMALE");
    if(this.gender.other)
      this.targetedAudience.genders.push("OTHER");
    for(let tag of this.hashtags.split(' '))
      this.targetedAudience.hashtags.push(tag);
    this.campaign.audiences.push(this.targetedAudience);
    this.targetedAudience = {
        fromAge: 15,
        toAge: 70,
        hashtags: new Array(),
        genders: new Array()
    }
    this.gender = {male: false, female: false, other: false}
    this.hashtags = '';
}

  removeAudience(i: number){
    this.campaign.audience.splice(i, 1);
  }


  open(selectedModal: any) {
    this.modalService.open(selectedModal).result
  }

  formatTime(){
    let time = '';
    if(this.time.hours < 10){
      time += '0'
    }
    time += this.time.hours;
    time += ':';
    if(this.time.minutes < 10)
      time += '0'
    time += this.time.minutes;
    return time;
  }

}

<div id="form">
    <h1>New Campaign</h1>
    <br>
    <!-- Basic campaign info -->
    <span style="font-size:20px; font-weight:bold">Basic info</span> <hr>
    <table class="w-100 py-2">
        <tr>
        <td class="right">Campaign type:</td>
        <td>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="campType" id="post" value="POST" [(ngModel)]="campaign.campaignType">
                <label class="form-check-label" for="inlineRadio1">Post</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="campType" id="story" value="STORY" [(ngModel)]="campaign.campaignType">
                <label class="form-check-label" for="inlineRadio2">Story</label>
            </div>
        </td></tr>
        <tr><td></td>
        <td>
            <div class="form-check">
                <input class="form-check-input" type="checkbox"
                [checked]="isLongTerm"
                (change)="isLongTerm = !isLongTerm"
                id="termType">
                <label class="form-check-label" style="float: left;" for="termType">Long term</label>
            </div>
        </td></tr>
        <tr><td class="right">Start date:</td>
        <td>
            <input type="date" id="startDate" [(ngModel)]="campaign.startDate" :min="minDate" class="mb-2">
            <!-- <form class="form-inline d-flex justify-content-center">
                <div class="form-group">
                    <div class="input-group">
                        <input class="form-control" placeholder="yyyy-mm-dd" name="dp" [(ngModel)]="startDate" ngbDatepicker
                            #d="ngbDatepicker">
                        <div class="input-group-append" style="height: 10px;">
                            <button class="btn btn-outline-secondary calendar" (click)="d.toggle()"
                                type="button"></button>
                        </div>
                    </div>
                </div>
            </form> -->
        </td></tr>
        <tr *ngIf="!isLongTerm"><td class="right">Choose a time:</td>
        <td>     
            <!-- <ngb-timepicker [minuteStep]="15" [(ngModel)]="time" name="timepicker" class="d-flex justify-content-center"></ngb-timepicker>    -->
            <!-- <b-form-timepicker [(ngModel)]="time" locale="rs" placeholder="Choose a time"></b-form-timepicker> -->
            <input type="number" [(ngModel)]="time.hours" name="time" placeholder="HH" min="0" max="23" class="form-control"> : 
            <input type="number" [(ngModel)]="time.minutes" name="time" placeholder="mm" min="0" max="59" class="form-control">
        </td></tr>
        <tr *ngIf="isLongTerm"><td class="right">Duration:</td>
        <td><input [(ngModel)]="duration" type="number" id="duration" min="1" class="form-control"></td></tr>
        <tr *ngIf="isLongTerm"><td class="right">Display per day:</td>
        <td><input [(ngModel)]="campaign.perDay" type="number" id="perDay" min="1" max="24" class="form-control"></td></tr>
    </table>
    
    <br>

    <!-- Ads -->
    <div id="ads">
        <span style="font-size:20px; font-weight:bold">Advertisments</span>
        <button class="btn btn-outline-success" style="float:right" (click)="open(adModal)"><i class="fa fa-plus"></i></button>
        <hr>
        <div *ngFor="let ad of campaign.ads, index as i" class="left">
            <button size="sm" class="btn btn-outline-danger" style="float:right" (click)="removeAd(i)"><i class="fa fa-trash"></i></button>
            <span><i>File:</i> {{ad.fileName}}</span>
            <span *ngIf="ad.description != ''"><br><i>Description:</i> {{ad.description}} </span>
            <span *ngIf="ad.url != ''"><br><i>Link:</i> {{ad.url}}</span>
            <hr>
        </div>
    </div>
    <br>

    <!-- Targeted audience -->
    <div id="audiences">
            <span style="font-size:20px; font-weight:bold">Target Audience</span>
            <button class="btn btn-outline-success" style="float:right" (click)="open(audienceModal)"><i class="fa fa-plus"></i></button>
            <hr>
            <div *ngFor="let audience of campaign.audiences, index as i" class="left">
                <button size="sm" class="btn btn-outline-danger" style="float:right" (click)="removeAudience(i)"><i class="fa fa-trash"></i></button>
                <span>{{audience.fromAge}} - {{audience.toAge}} yo</span>
                <span *ngFor="let gender of audience.genders, index as k"> | {{gender.toLowerCase()}} </span> <br>
                <span *ngFor="let tag of audience.hashtags, index as l"> #{{tag}} </span>
                <hr>
            </div>
    </div>
    
    <br>
    <button type="submit" class="btn btn-primary" style="width:200px;" (click)="createCampaign()">Save changes</button><br>
    
    <!-- Ad modal -->
    <ng-template #adModal let-modal>
        <div class="modal-header">
          <h4 class="modal-title" id="ad-modal-title">Advertisment</h4>
          <button type="button" class="btn close" aria-label="Close" (click)="modal.close('Cross click')">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <table class="w-100">
                <tr><td>Choose images:</td><td>
                <input type="file" ref="image" (change)="onImageUpload($event)" class="form-control" required>
                </td></tr>
                <tr><td>Description:</td>
                <td><textarea [(ngModel)]="ad.description" type="text" id="description" placeholder="Description" rows="3" class="form-control"></textarea></td></tr>
                <tr><td>Ad URL:</td>
                <td><input [(ngModel)]="ad.url" type="url" id="link" placeholder="Link" class="form-control"></td></tr>
            </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-success" (click)="addAd()">Add</button>
          <button type="button" class="btn btn-secondary" (click)="modal.close('Save click')">Close</button>
        </div>
    </ng-template>
    <!-- Targeted audience modal -->
    <ng-template #audienceModal let-modal>
        <div class="modal-header">
          <h4 class="modal-title" id="audience-modal-title">Audience</h4>
          <button type="button" class="btn close" aria-label="Close" (click)="modal.close('Cross click')">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <b>Age</b>
            <table class="w-100">
                <tr><td>From:</td>
                <td><input [(ngModel)]="targetedAudience.fromAge" type="number" id="fromAge" min="15" max="70" placeholder="From" class="form-control"></td></tr>
                <tr><td>To:</td>
                <td><input [(ngModel)]="targetedAudience.toAge" type="number" id="toAge" min="15" max="70" placeholder="To" class="form-control"></td></tr>
            </table>
            <br>
            <b>Gender</b><br>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="campType" id="male" value="MALE" [(ngModel)]="gender.male">
                <label class="form-check-label">Male</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="campType" id="female" value="FEMALE" [(ngModel)]="gender.female">
                <label class="form-check-label">Female</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="campType" id="other" value="OTHER" [(ngModel)]="gender.other">
                <label class="form-check-label">Other</label>
            </div>
            <br>
            <b>HashTags</b> <!-- TODO: hashtags input-->
            <!-- <b-form-tags
                [(ngModel)]="targetedAudience.hashtags"
                tag-variant="primary"
                tag-pills
                separator=" "
                placeholder="Enter new tags separated by space"
            ></b-form-tags> -->
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-success" (click)="addAudience()">Add</button>
            <button type="button" class="btn btn-secondary" (click)="modal.close('Save click')">Close</button>
        </div>
    </ng-template>
</div>

// frontend/my-app/src/components/AddCampaign.vue
<template>
    <div id="form">
        <h1 class="brandName">New Campaign</h1>
        <br>
        <!-- Basic campaign info -->
        <span style="font-size:20px; font-weight:bold">Basic info</span> <hr>
        <table class="w-100 py-2">
            <tr>
            <td>Campaign type:</td>
              <td><b-form-radio-group
                v-model="campaign.campaignType"
                :options="campType"
                class="mb-3"
                value-field="value"
                text-field="text"
                disabled-field="notEnabled"
              ></b-form-radio-group></td>
            </tr>
            <tr><td></td>
            <td><b-form-checkbox
              id="termType"
              v-model="campaign.termType"
              name="termType"
              value="LONG_TERM"
              unchecked-value="SHORT_TERM">
              Long term
            </b-form-checkbox>
            </td></tr>
            <tr><td>Start date:</td>
            <td><b-form-datepicker id="startDate" v-model="startDate" :min="minDate" class="mb-2"></b-form-datepicker></td></tr>
            <tr v-if="campaign.termType == 'SHORT_TERM'"><td>Choose a time:</td>
            <td>        
                <b-form-timepicker v-model="time" locale="rs" placeholder="Choose a time"></b-form-timepicker>
            </td></tr>
            <tr v-if="campaign.termType == 'LONG_TERM'"><td>Duration:</td>
            <td><b-form-input v-model="duration" type="number" id="duration" min="1">{{duration}}</b-form-input></td></tr>
            <tr v-if="campaign.termType == 'LONG_TERM'"><td>Display per day:</td>
            <td><b-form-input v-model="campaign.perDay" type="number" id="perDay" min="1" max="24">{{campaign.perDay}}</b-form-input></td></tr>
          </table>
          <br>

          <!-- Ads -->
          <div id="ads">
            <span style="font-size:20px; font-weight:bold">Advertisments</span>
            <b-button variant="outline-success" style="float:right" v-b-modal.modal-ads><i class="fa fa-plus"></i></b-button>
            <hr>
            <div v-for="(ad,i) in campaign.ads" :key="i" class="left">
                <b-btn size="sm" variant="outline-danger" class="float-right" @click="removeAd(i)"><i class="fa fa-trash"></i></b-btn>
                <span><i>File:</i> {{ad.fileName}}</span>
                <span v-if="ad.description != ''"><br><i>Description:</i> {{ad.description}} </span>
                <span v-if="ad.url != ''"><br><i>Link:</i> {{ad.url}}</span>
                <hr>
            </div>
          </div>
          <br>

          <!-- Targeted audience -->
          <div id="audiences">
                <span style="font-size:20px; font-weight:bold">Target Audience</span>
                <b-button variant="outline-success" style="float:right" v-b-modal.modal-audience><i class="fa fa-plus"></i></b-button>
                <hr>
                <div v-for="(audience,i) in campaign.audiences" :key="i" class="left">
                    <b-btn size="sm" variant="outline-danger" class="float-right" @click="removeAudience(i)"><i class="fa fa-trash"></i></b-btn>
                    <span>{{audience.fromAge}} - {{audience.toAge}} yo</span>
                    <span v-for="(gender,k) in audience.genders" :key="k"> | {{gender.toLowerCase()}} </span> <br>
                    <span v-for="(tag, l) in audience.hashtags" :key="l"> #{{tag}} </span>
                    <hr>
                </div>
          </div>
          
          <br>
          <b-button type="submit" variant="primary" style="width:200px;" @click="createCampaign()">Save changes</b-button><br>
          
          <!-- Ad modal -->
          <b-modal id="modal-ads" title="Advertisment" @ok="addAd">
                <div>
                    <table class="w-100">
                        <tr><td>Choose images:</td><td>
                        <!-- <input type="file" ref="image" class="form-control" required> -->
                        <b-form-file
                            v-model="file"
                            :state="Boolean(file)"
                            placeholder="Choose file or drop it here..."
                            drop-placeholder="Drop file here..."
                        ></b-form-file>
                        </td></tr>
                        <tr><td>Description:</td>
                        <td><b-form-textarea v-model="ad.description" type="text" id="description" placeholder="Description" rows="3"></b-form-textarea></td></tr>
                        <tr><td>Ad URL:</td>
                        <td><b-form-input v-model="ad.url" type="url" id="link" placeholder="Link"></b-form-input></td></tr>
                    </table>
                    <br>
                </div>
                <template #modal-footer="{ ok, cancel }">
                    <b-button variant="success" @click="ok()">
                        Add
                    </b-button>
                    <b-button variant="secondary" @click="cancel()">
                        Cancel
                    </b-button>
                </template>
          </b-modal>

          <!-- Targeted audience modal -->
          <b-modal id="modal-audience" title="Audience" @ok="addAudience">
                <div>
                    <b>Age</b>
                    <!-- <b-form-input id="ageRange" v-model="age" type="range" min="15" max="75"></b-form-input> -->
                    <table class="w-100">
                        <tr><td>From:</td>
                        <td><b-form-input v-model="targetedAudience.fromAge" type="number" id="fromAge" min="15" max="70" placeholder="From"></b-form-input></td></tr>
                        <tr><td>To:</td>
                        <td><b-form-input v-model="targetedAudience.toAge" type="number" id="toAge" min="15" max="70" placeholder="To"></b-form-input></td></tr>
                    </table>
                    <br>
                    <b>Gender</b>
                    <b-form-checkbox-group
                        id="genderM"
                        v-model="targetedAudience.genders"
                        name="genderM"
                        :options="genderOpts">
                    </b-form-checkbox-group>
                    <br>
                    <b>HashTags</b>
                    <b-form-tags
                        v-model="targetedAudience.hashtags"
                        tag-variant="primary"
                        tag-pills
                        separator=" "
                        placeholder="Enter new tags separated by space"
                    ></b-form-tags>
                </div>
                <template #modal-footer="{ ok, cancel }">
                    <b-button variant="success" @click="ok()">
                        Add
                    </b-button>
                    <b-button variant="secondary" @click="cancel()">
                        Cancel
                    </b-button>
                </template>
            </b-modal>
        </div>
</template>

<script>
import moment from 'moment'
import { CAMPAIGN_PATH, IMAGE_PATH, ROLE_AGENT, SERVER_NOT_RESPONDING } from '../util/constants'
import { getRoleFromToken, getUsernameFromToken } from '../util/token'
export default {
    data(){
        return{
            campaign:{
                username: getUsernameFromToken(),
                campaignType: 'POST',
                termType:'SHORT_TERM',
                startDate: '',
                endDate: null,
                perDay: 1,
                audiences: [],
                ads: []
            },
            files: [],
            file: null,
            imagesToUpload: null,
            ad: {
                url: '',
                description: '',
                fileName: ''
            },
            targetedAudience: {
                fromAge: 15,
                toAge: 70,
                hashtags: [],
                genders: []
            },

            minDate: new Date(),
            startDate: new Date(),
            time: '12:00',
            duration: 1,
            campType:[
                { text: 'Post', value: 'POST' },
                { text: 'Story', value: 'STORY' }
            ],
            genderOpts:[
                { text: 'Male', value: 'MALE'},
                { text: 'Female', value: 'FEMALE'},
                { text: 'Other', value: 'OTHER'}
            ],
            
        }
    },
    beforeMount(){
        if(getRoleFromToken() != ROLE_AGENT)
            window.location.href = "/"
        let date = new Date()
        this.minDate.setDate(date.getDate() + 1);
        this.startDate.setDate(date.getDate() + 1);
    },
    methods: {
        makeToast(message, variant) {
        this.$root.$bvToast.toast(message, {
                              title: `Nistagram`,
                              autoHideDelay: 5000,
                              variant: variant,
                              toaster: 'b-toaster-bottom-right',
                              solid: true,
                              appendToast: false
                            })
        },
        createCampaign(){
            if(this.campaign.termType == "LONG_TERM"){
                this.campaign.startDate = moment(String(this.startDate)).format('YYYY-MM-DD HH:mm');
                this.campaign.endDate = new Date(this.startDate);
                this.campaign.endDate.setDate(this.campaign.endDate.getDate() + Number(this.duration));
                this.campaign.endDate = moment(String(this.campaign.endDate)).format('YYYY-MM-DD HH:mm');
            }else if(this.campaign.termType == "SHORT_TERM"){
                this.campaign.startDate = moment(String(this.startDate)).format('YYYY-MM-DD');
                this.campaign.startDate = this.campaign.startDate + " " + this.time;
            }
            this.onImageUpload();

            this.axios.post(IMAGE_PATH, this.imagesToUpload, {
                headers:{
                    Accept: 'application/json',
                    'Content-Type':'multipart/form-data'
                }
            }).then(response => {
                console.log(response.data);
                this.makeToast("Medias have been uploaded.", "success");
                this.axios.post(CAMPAIGN_PATH, this.campaign)
                    .then(() => {
                        this.makeToast("Campaign made successfully", "success");
                        window.location.href = "/user/" + this.campaign.username;
                        // TODO: Redirect to all campaign page when added
                    }).catch(err => {
                        if(!err.response)
                              this.makeToast(SERVER_NOT_RESPONDING, "danger");
                        else
                            this.makeToast("Something went wrong while creating campaign", "danger");
                    })
            })
        },
        addAudience(){
            if(this.targetedAudience.fromAge > this.targetedAudience.toAge){ // TODO: Prevent modal close, prettier validation
                this.makeToast("Invalid age range!", "danger");
                return;
            }
            this.campaign.audiences.push(this.targetedAudience);
            this.targetedAudience = {
                fromAge: 15,
                toAge: 70,
                hashtags: [],
                genders: []
            }
        },

        removeAudience(i){
            this.campaign.audiences.splice(i, 1);
        },

        addAd(){
            if(this.file == null){      // TODO: Prevent modal close, prettier validation
                this.makeToast("Media must be specified!", "danger")
                return;
            }
            // this.files.push(this.$refs.image.files[0]);
            // this.ad.fileName = this.$refs.image.files[0].name;
            this.files.push(this.file);
            this.ad.fileName = this.file.name;
            this.file = null;
            this.campaign.ads.push(this.ad);
            this.ad = {
                url: '',
                description: '',
                fileName: ''
            }
        },

        removeAd(i){
            this.campaign.ads.splice(i, 1);
            this.files.splice(i, 1);
        },

        onImageUpload(){
            this.imagesToUpload = new FormData();
            for(let file of this.files){
                this.imagesToUpload.append("file", file);
            }
        },
        
    }
}
</script>
<style scoped>
td{
  padding-top: 5px;
  padding-bottom: 5px
}

#form {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  background: white;
  text-align: center;
  color: #2c3e50;
  margin: auto;
  margin-top: 40px;
  margin-bottom: 40px;
  width: 50%;
  border: 3px solid lightblue;
  padding: 50px;
}

.left {
    text-align: left;
}
</style>
