// monolit-app/webshop-front/src/app/components/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { getRoleFromToken, getUsernameFromToken, removeToken } from 'src/app/util/tokenUtil';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

  constructor(private router: Router) { }

  ngOnInit(): void {
  }

  getUsername(){
    return getUsernameFromToken();
  }

  getRole(){
    return getRoleFromToken();
  }

  logout(){
    removeToken();
    this.router.navigate(['/login'], {skipLocationChange:true});
  }

  shoppingCart(){
    this.router.navigate(['/shopping-cart']);
  }

}

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #F7F4EA;">
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">
            <img src="assets/shopping.png" width="40" height="40" alt="Jenkins" />
        </a>
        <ul class="navbar-nav mr-auto" style="font-size: 20px;">
            <li class="nav-item">
                <button class="heart nav-btn" [routerLink]="'/discover'">
                    <i class="fas fa-globe"></i>
                </button>
            </li>
            <li class="nav-item" *ngIf="getUsername() != null && getRole() == 'ROLE_AGENT'">
                <button class="heart nav-btn" [routerLink]="['/shop', getUsername()]">
                    <i class="fas fa-store"></i>
                </button>
            </li>
            <li class="nav-item">
                <button *ngIf="getUsername() != null && getRole() == 'ROLE_USER'" class="heart nav-btn" (click)="shoppingCart()">
                    <i class="fas fa-shopping-cart"></i>
                </button>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" *ngIf="getUsername() == null" [routerLink]="'/registration'" routerLinkActive="active" >Registration</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" *ngIf="getUsername() == null" [routerLink]="'/login'" routerLinkActive="active" >Login</a>
            </li>
            
            <li class="nav-item">
                <button *ngIf="getUsername() != null" class="heart nav-btn" (click)="logout()">
                    <i class="fas fa-sign-out-alt"></i>
                </button>
            </li>
        </ul>
    </div>
</nav>

// frontend/my-app/src/components/Navbar.vue
<template>
  <div id="navbarPage">
    <nav class="navbar navbar-expand navbar-light" style="background-color: #e3f2fd;">
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="/">
            <img src="../assets/logo.png" height="40" alt="" />
        </a>
        <form style="padding: 0px 0px 0px 60px;">
          <input type="text" class="search-input" v-model="searchInput">
          <button @click="search()" type="submit" class="search-btn">
            <i class="fas fa-search"></i>
          </button>
          <br>
          <div>
          <b-form-radio-group
            v-model="selected"
            :options="options"
            class="mb-3"
            value-field="item"
            text-field="name"
            disabled-field="notEnabled"
          ></b-form-radio-group>
        </div>

        </form>

        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item">
                <button class="nav-btn" @click='discoverPage'>
                  <i class="fas fa-globe"></i>
                </button>
            </li>
            <li class="nav-item" v-if="username != null && role == 'ROLE_USER'">
                <button class="nav-btn">
                  <i class="fas fa-envelope"></i>
                </button>
            </li>
            <li class="nav-item" v-if="username != null && role == 'ROLE_USER'">
                <button class="heart nav-btn" @click="notificationPage">
                  <i class="fas fa-heart"></i>
                </button>
            </li>
            <li class="nav-item" v-if="username != null && isAdmin ==true">
                <button class="nav-btn" @click='inappropriateContent'>
                  <i class="fas fa-ban"></i>
                </button>
            </li>
            <li class="nav-item" v-if="username != null && isAdmin ==true">
                <button class="nav-btn" @click='profileVerification'>
                  <i class="fas fa-user-check"></i>
                </button>
            </li>
            <li class="nav-item" v-if="username != null && isAdmin ==true">
                <button class="nav-btn">
                  <i class="fas fa-user-secret"></i>
                </button>
            </li>
            <li class="nav-item" v-if="username != null && role == 'ROLE_USER'">
                <button class="nav-btn" @click='myProfile'>
                  <i class="fas fa-user"></i>
                </button>
            </li>
            <li class="nav-item" v-if="username != null">
                <button class="nav-btn" @click="logout">
                  <i class="fas fa-sign-out-alt"></i>
                </button>
            </li>
        </ul>
    </div>
    </nav>
  </div>
</template>


<script>
import { getRoleFromToken, getUsernameFromToken, removeToken } from '../util/token';
export default {
  name: 'Navbar',
  data() {
      return {
        selected: 'profile',
        options: [
          { item: 'profile', name: 'Profiles' },
          { item: 'tag', name: 'Tags' },
          { item: 'location', name: 'Locations' },
        ],
        username: getUsernameFromToken(),
        searchInput:'',
        role: getRoleFromToken(),
      }
  },

  methods:{
    myProfile:function(){
      window.location.href = "/user/" + this.username;
    },
    logout: function(){
      removeToken();
      window.location.href = "/"
    },
    inappropriateContent:function(){
      window.location.href = "/inappropriate_content";
    },
    discoverPage:function(){
      window.location.href = "/discover";
    },
    notificationPage:function(){
      window.location.href = "/notification";
    },
    search: function() {
      localStorage.setItem("name", this.selected);
      localStorage.setItem("find", this.searchInput);
      this.$router.push({path: '/search'})        
    },
    profileVerification: function(){
      window.location.href = "/all_requests";
    }
  },
}
</script>

<style>
.nav-item{
  font-size: 25px;
}
.clickable:hover{
  cursor: pointer;
}

.fas{
  cursor: pointer;
  transition: all 0.5s ease;
}

.nav-btn {
    color:black;
    padding: 0.5rem;
    font-size: 2rem;
    border: none;
    background: #e3f2fd;
}
.nav-btn:hover{
    background: #0275d8;
    color: white;
    border-radius: 7px;
}
.heart:hover{
  color:red;
}
.search{
  padding: 0.5rem;
  font-size: 2rem;
}
.search:hover{
  border-radius: 0px;
  background: #e3f2fd;
  color: #0275d8;
}
.search-btn,
.search-input{
    padding: 0.5rem;
    font-size: 20px;
    border: none;
    background: white;
}
.search-btn{
    color: black;
    background: #e3f2fd;
    cursor: pointer;
    font-size: 25px;
    transition: all 0.3s ease;
}
.search-btn:hover{
    color: #0275d8;
    background: #e3f2fd;
}

</style>
